mybatis:
  mapper-locations: classpath:mapping/*.xml
logging:
  level:
    root: info
spring:
  datasource:
    name: miaosha
    url: jdbc:mysql://localhost:3306/miaosha
    username: root
    password: wangshuai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    database: 0
    timeout: 1000s
  output:
    ansi:
      enabled: ALWAYS
mq:
  nameserver:
    addr: 192.168.56.101:9876
  topicname: stock
